[package]
name = "octobors"
version = "0.1.0"
authors = ["Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"

[dependencies]
# Error helpers
anyhow = "1.0"
# Used for making all of the requests to github
octocrab = "0.8"
# De/serialization support
serde = { version = "1.0", features = ["derive"] }
# JSON support
serde_json = "1.0"
# Argument parsing
structopt = "0.3"
# Async runtime, note we're stuck on 0.2 until reqwest/hyper update to 0.3
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
